### ISSUE TITLE
Not have enough RAM to run the program

### ISSUE THREAD

**Issue by Sum-low** [sortmerna/sortmerna#429]
I could not run the sortmerna on my computer, because it does not have enough RAM（my computer has 20G RAM ）

ERROR is: Segmentation fault (core dumped). 

And I will list the code at the end. 

Could you tell me how much memory SortMeRNA typically requires? Is it because my input files are too large? Are there any solutions to reduce the memory usage?

Thank you！

`sortmerna --ref /home/lx/sortmerna/sortmerna/data/rRNA_databases/silva-euk-18s-id95.fasta --ref /home/lx/sortmerna/sortmerna/data/rRNA_databases/silva-euk-28s-id98.fasta --reads /home/lx/RIP_seq/fastq/trimmed/VIRMA_IP1_forward_val_1.fq.gz --reads /home/lx/RIP_seq/fastq/trimmed/VIRMA_IP1_reverse_val_2.fq.gz --aligned /home/lx/RIP_seq/fastq/VIRMA_IP1_forward_rRNA --aligned /home/lx/RIP_seq/fastq/VIRMA_IP1_reverse_rRNA --other /home/lx/RIP_seq/fastq/VIRMA_IP1_forward_fliter --other /home/lx/RIP_se\q/fastq/VIRMA_IP1_reverse_fliter --fastx --threads 4
[process:1393] === Options processing starts ... ===
Found value: sortmerna
Found flag: --ref
Found value: /home/lx/sortmerna/sortmerna/data/rRNA_databases/silva-euk-18s-id95.fasta of previous flag: --ref
Found flag: --ref
Found value: /home/lx/sortmerna/sortmerna/data/rRNA_databases/silva-euk-28s-id98.fasta of previous flag: --ref
Found flag: --reads
Found value: /home/lx/RIP_seq/fastq/trimmed/VIRMA_IP1_forward_val_1.fq.gz of previous flag: --reads
Found flag: --reads
Found value: /home/lx/RIP_seq/fastq/trimmed/VIRMA_IP1_reverse_val_2.fq.gz of previous flag: --reads
Found flag: --aligned
Found value: /home/lx/RIP_seq/fastq/VIRMA_IP1_forward_rRNA of previous flag: --aligned
Found flag: --aligned
Found value: /home/lx/RIP_seq/fastq/VIRMA_IP1_reverse_rRNA of previous flag: --aligned
Found flag: --other
Found value: /home/lx/RIP_seq/fastq/VIRMA_IP1_forward_fliter of previous flag: --other
Found flag: --other
Found value: /home/lx/RIP_seq/fastq/VIRMA_IP1_reverse_fliter of previous flag: --other
Found flag: --fastx
Previous flag: --fastx is Boolean. Setting to True
Found flag: --threads
Found value: 4 of previous flag: --threads
[process:1483] Processing option: aligned with value: /home/lx/RIP_seq/fastq/VIRMA_IP1_forward_rRNA
[process:1483] Processing option: aligned with value: /home/lx/RIP_seq/fastq/VIRMA_IP1_reverse_rRNA
[process:1483] Processing option: fastx with value:
[process:1483] Processing option: other with value: /home/lx/RIP_seq/fastq/VIRMA_IP1_forward_fliter
[process:1483] Processing option: other with value: /home/lx/RIP_seq/fastq/VIRMA_IP1_reverse_fliter
[process:1483] Processing option: reads with value: /home/lx/RIP_seq/fastq/trimmed/VIRMA_IP1_forward_val_1.fq.gz
[opt_reads:98] Processing reads file [1] out of total [2] files
[process:1483] Processing option: reads with value: /home/lx/RIP_seq/fastq/trimmed/VIRMA_IP1_reverse_val_2.fq.gz
[opt_reads:98] Processing reads file [2] out of total [2] files
[process:1483] Processing option: ref with value: /home/lx/sortmerna/sortmerna/data/rRNA_databases/silva-euk-18s-id95.fasta
[opt_ref:158] Processing reference [1] out of total [2] references
[opt_ref:206] File "/home/lx/sortmerna/sortmerna/data/rRNA_databases/silva-euk-18s-id95.fasta" exists and is readable
[process:1483] Processing option: ref with value: /home/lx/sortmerna/sortmerna/data/rRNA_databases/silva-euk-28s-id98.fasta
[opt_ref:158] Processing reference [2] out of total [2] references
[opt_ref:206] File "/home/lx/sortmerna/sortmerna/data/rRNA_databases/silva-euk-28s-id98.fasta" exists and is readable
[process:1483] Processing option: threads with value: 4
[process:1503] === Options processing done ===
[process:1504] Alignment type: [best:1 num_alignments:1 min_lis:2 seeds:2]
[validate_kvdbdir:1242] 'workdir' option was not provided. Using USERDIR to set the working directory: ""
[validate_kvdbdir:1248] Key-value DB location "/home/lx/sortmerna/run/kvdb"
[validate_idxdir:1214] Using index directory: "/home/lx/sortmerna/run/idx"
[validate_idxdir:1230] IDX directory: "/home/lx/sortmerna/run/idx" exists and is not empty
[validate_readb_dir:1306] Using split reads directory : "/home/lx/sortmerna/run/readb"
[validate_readb_dir:1319] split reads directory : "/home/lx/sortmerna/run/readb" exists and is empty
[main:62] Running command:
sortmerna --ref /home/lx/sortmerna/sortmerna/data/rRNA_databases/silva-euk-18s-id95.fasta --ref /home/lx/sortmerna/sortmerna/data/rRNA_databases/silva-euk-28s-id98.fasta --reads /home/lx/RIP_seq/fastq/trimmed/VIRMA_IP1_forward_val_1.fq.gz --reads /home/lx/RIP_seq/fastq/trimmed/VIRMA_IP1_reverse_val_2.fq.gz --aligned /home/lx/RIP_seq/fastq/VIRMA_IP1_forward_rRNA --aligned /home/lx/RIP_seq/fastq/VIRMA_IP1_reverse_rRNA --other /home/lx/RIP_seq/fastq/VIRMA_IP1_forward_fliter --other /home/lx/RIP_seq/fastq/VIRMA_IP1_reverse_fliter --fastx --threads 4
[Index:102] Found 8 non-empty index files. Skipping indexing.
[init:108] Readfeed init started
[define_format:881] file: "/home/lx/RIP_seq/fastq/trimmed/VIRMA_IP1_forward_val_1.fq.gz" is FASTQ gzipped
[define_format:881] file: "/home/lx/RIP_seq/fastq/trimmed/VIRMA_IP1_reverse_val_2.fq.gz" is FASTQ gzipped
[count_reads:915] started count  ...
[next:322] EOF FWD reached. Total reads: 61300634
[next:322] EOF REV reached. Total reads: 61300634
[count_reads:945] done count. Elapsed time: 11245.7 sec. Total reads: 122601268
[init_split_files:967] added file: /home/lx/sortmerna/run/readb/fwd_0.fq.gz
[init_split_files:967] added file: /home/lx/sortmerna/run/readb/rev_0.fq.gz
[init_split_files:967] added file: /home/lx/sortmerna/run/readb/fwd_1.fq.gz
[init_split_files:967] added file: /home/lx/sortmerna/run/readb/rev_1.fq.gz
[init_split_files:967] added file: /home/lx/sortmerna/run/readb/fwd_2.fq.gz
[init_split_files:967] added file: /home/lx/sortmerna/run/readb/rev_2.fq.gz
[init_split_files:967] added file: /home/lx/sortmerna/run/readb/fwd_3.fq.gz
[init_split_files:967] added file: /home/lx/sortmerna/run/readb/rev_3.fq.gz
[split:605] start splitting. Using number of splits equals number of processing threads: 4

[next:322] EOF FWD reached. Total reads: 61300634
[next:322] EOF REV reached. Total reads: 61300634
[split:717] Done splitting. Reads count: 122601268 Runtime sec: 3433.03

[init:135] Readfeed init done in sec [14678.8]
[store_to_db:292] Stored Reads statistics to DB:
     all_reads_count= 122601268 all_reads_len= 15260118355 min_read_len= 50 max_read_len= 150 total_aligned= 0 total_aligned_id= 0 total_aligned_cov= 0 total_aligned_id_cov= 0 total_denovo= 0 num_short= 0 reads_matched_per_db= TODO is_stats_calc= 0 is_total_reads_mapped_cov= 0

[align:143] ==== Starting alignment ====
[align:146] Number of cores: 8
[align:163] Using number of Processor threads: 4
[Refstats:60] Index Statistics calculation starts ... done in: 0.865999 sec
[align:185] Loading index: 0 part: 1/1 Memory KB: 6 ...
[align:190] done in [1.4995] sec Memory KB: 373
[align:193] Loading references ...
[align:197] done in [0.112235] sec. Memory KB: 387
[align2:70] Processor 0 thread 140682500245248 started
[align2:70] Processor 1 thread 140682508699392 started
[align2:70] Processor 2 thread 140682517153536 started
[align2:70] Processor 3 thread 140682947266304 started

[next:455] EOF FWD reached. Total reads: 15325158
[next:455] EOF REV reached. Total reads: 15325158
[align2:133] Processor 2 thread 140682517153536 done. Processed 30650316 reads. Skipped already processed: 0 reads Aligned reads (passing E-value): 7163079 Runtime sec: 6838.19
[next:455] EOF FWD reached. Total reads: 15325159
[next:455] EOF REV reached. Total reads: 15325159
[align2:133] Processor 0 thread 140682500245248 done. Processed 30650318 reads. Skipped already processed: 0 reads Aligned reads (passing E-value): 7156628 Runtime sec: 6958.56
[next:455] EOF FWD reached. Total reads: 15325159
[next:455] EOF REV reached. Total reads: 15325159
[align2:133] Processor 1 thread 140682508699392 done. Processed 30650318 reads. Skipped already processed: 0 reads Aligned reads (passing E-value): 7192186 Runtime sec: 7076.94
[next:455] EOF FWD reached. Total reads: 15325158
[next:455] EOF REV reached. Total reads: 15325158
[align2:133] Processor 3 thread 140682947266304 done. Processed 30650316 reads. Skipped already processed: 0 reads Aligned reads (passing E-value): 7179987 Runtime sec: 7281.38
[align:220] done index: 0 part: 1 in 7281.38 sec Memory KB: 13419
[align:227] Index and References unloaded in 0.107187 sec. Memory KB: 13419
[align:185] Loading index: 1 part: 1/1 Memory KB: 13419 ...
[align:190] done in [1.40843] sec Memory KB: 13435
[align:193] Loading references ...
[align:197] done in [0.118384] sec. Memory KB: 13449
[align2:70] Processor 0 thread 140682947266304 started
[align2:70] Processor 1 thread 140682517153536 started
[align2:70] Processor 3 thread 140682500245248 started
[align2:70] Processor 2 thread 140682508699392 started
Segmentation fault (core dumped)`

**Comment by biocodz** [comment]
Could you, please, provide the following info
```
sortmerna -version
du -sh /home/lx/sortmerna/run/kvdb
ls -l /home/lx/sortmerna/run/kvdb
du -sh /home/lx/sortmerna/run/readb
ls -l /home/lx/sortmerna/run/readb
cat /home/lx/sortmerna/run/readb/readfeed
```
?

**Comment by Sum-low** [comment]
sure. I’m sorry for not giving all the details.

`sortmerna -version
[process:1393] === Options processing starts ... ===
Found value: sortmerna
Found flag: -version
[process:1483] Processing option: version with value:

SortMeRNA version 4.3.6
Build Date: Aug 16 2022
sortmerna_build_git_sha:@db8c1983765f61986b46ee686734749eda235dcc@
sortmerna_build_git_date:@2022/08/16 11:42:59@

du -sh /home/lx/sortmerna/run/kvdb
2.4G    /home/lx/sortmerna/run/kvdb

ls -l /home/lx/sortmerna/run/kvdb
total 2487948
-rw-r--r-- 1 lx lx 67908158 Sep  5 02:31 000380.sst
-rw-r--r-- 1 lx lx 67896268 Sep  5 03:22 000521.sst
-rw-r--r-- 1 lx lx  1325539 Sep  5 03:33 000550.sst
-rw-r--r-- 1 lx lx 67918834 Sep  5 03:44 000582.sst
-rw-r--r-- 1 lx lx 67907219 Sep  5 03:45 000583.sst
-rw-r--r-- 1 lx lx 63747685 Sep  5 03:45 000584.sst
-rw-r--r-- 1 lx lx 67912701 Sep  5 03:50 000599.sst
-rw-r--r-- 1 lx lx 67907495 Sep  5 03:50 000600.sst
-rw-r--r-- 1 lx lx 67906611 Sep  5 03:50 000601.sst
-rw-r--r-- 1 lx lx 67915678 Sep  5 03:51 000604.sst
-rw-r--r-- 1 lx lx 67895296 Sep  5 03:51 000605.sst
-rw-r--r-- 1 lx lx 37021351 Sep  5 03:51 000606.sst
-rw-r--r-- 1 lx lx 67896148 Sep  5 04:01 000631.sst
-rw-r--r-- 1 lx lx 67906933 Sep  5 04:01 000632.sst
-rw-r--r-- 1 lx lx 67918086 Sep  5 04:01 000633.sst
-rw-r--r-- 1 lx lx 67906347 Sep  5 04:02 000636.sst
-rw-r--r-- 1 lx lx 55528663 Sep  5 04:02 000637.sst
-rw-r--r-- 1 lx lx 67885896 Sep  5 04:06 000649.sst
-rw-r--r-- 1 lx lx 67887596 Sep  5 04:06 000650.sst
-rw-r--r-- 1 lx lx 38743901 Sep  5 04:07 000651.sst
-rw-r--r-- 1 lx lx 67924755 Sep  5 04:12 000666.sst
-rw-r--r-- 1 lx lx 67905792 Sep  5 04:12 000667.sst
-rw-r--r-- 1 lx lx 67905833 Sep  5 04:12 000668.sst
-rw-r--r-- 1 lx lx 67905774 Sep  5 04:13 000669.sst
-rw-r--r-- 1 lx lx 65490327 Sep  5 04:13 000672.sst
-rw-r--r-- 1 lx lx 67906775 Sep  5 04:17 000684.sst
-rw-r--r-- 1 lx lx 67896277 Sep  5 04:18 000685.sst
-rw-r--r-- 1 lx lx 67891473 Sep  5 04:18 000686.sst
-rw-r--r-- 1 lx lx 67888510 Sep  5 04:18 000687.sst
-rw-r--r-- 1 lx lx 65573673 Sep  5 04:19 000690.sst
-rw-r--r-- 1 lx lx 67877713 Sep  5 04:27 000708.sst
-rw-r--r-- 1 lx lx 67883232 Sep  5 04:27 000709.sst
-rw-r--r-- 1 lx lx 67876846 Sep  5 04:27 000710.sst
-rw-r--r-- 1 lx lx 51679957 Sep  5 04:28 000712.sst
-rw-r--r-- 1 lx lx 11983534 Sep  5 04:28 000714.sst
-rw-r--r-- 1 lx lx 67900179 Sep  5 04:28 000715.sst
-rw-r--r-- 1 lx lx 45928402 Sep  5 04:29 000716.sst
-rw-r--r-- 1 lx lx 12010155 Sep  5 04:29 000718.sst
-rw-r--r-- 1 lx lx 12017383 Sep  5 04:31 000720.sst
-rw-r--r-- 1 lx lx 48018369 Sep  5 04:33 000721.log
-rw-r--r-- 1 lx lx 11998984 Sep  5 04:32 000722.sst
-rw-r--r-- 1 lx lx 67878081 Sep  5 04:32 000723.sst
-rw-r--r-- 1 lx lx 67881526 Sep  5 04:33 000724.sst
-rw-r--r-- 1 lx lx 55549697 Sep  5 04:33 000725.sst
-rw-r--r-- 1 lx lx       16 Sep  4 19:14 CURRENT
-rw-r--r-- 1 lx lx       36 Sep  4 19:14 IDENTITY
-rw-r--r-- 1 lx lx        0 Sep  4 19:14 LOCK
-rw-r--r-- 1 lx lx  1807582 Sep  5 04:33 LOG
-rw-r--r-- 1 lx lx    46669 Sep  5 04:32 MANIFEST-000004
-rw-r--r-- 1 lx lx     6504 Sep  4 19:14 OPTIONS-000007

du -sh /home/lx/sortmerna/run/readb
6.0G    /home/lx/sortmerna/run/readb

 ls -l /home/lx/sortmerna/run/readb
total 6276596
-rw-r--r-- 1 lx lx 648725915 Sep  4 22:36 fwd_0.fq.gz
-rw-r--r-- 1 lx lx 653543637 Sep  4 22:50 fwd_1.fq.gz
-rw-r--r-- 1 lx lx 656703365 Sep  4 23:04 fwd_2.fq.gz
-rw-r--r-- 1 lx lx 660974452 Sep  4 23:18 fwd_3.fq.gz
-rw-r--r-- 1 lx lx       971 Sep  4 23:18 readfeed
-rw-r--r-- 1 lx lx 948145087 Sep  4 22:36 rev_0.fq.gz
-rw-r--r-- 1 lx lx 960648283 Sep  4 22:50 rev_1.fq.gz
-rw-r--r-- 1 lx lx 918949395 Sep  4 23:04 rev_2.fq.gz
-rw-r--r-- 1 lx lx 979528213 Sep  4 23:18 rev_3.fq.gz

cat /home/lx/sortmerna/run/readb/readfeed
# format of this file:
#   time
#   num_orig_files
#   num_sense
#   num_splits
#   num_reads_tot
#   [
#     file
#     size
#     reads
#     zip
#     fastq/a
#   ] for each file both original and split

Wed Sep  4 23:18:50 2024

2
2
4
122601268
/home/lx/RIP_seq/fastq/trimmed/VIRMA_IP1_forward_val_1.fq.gz
2618337302
61300634
1
fastq
/home/lx/RIP_seq/fastq/trimmed/VIRMA_IP1_reverse_val_2.fq.gz
3805174809
61300634
1
fastq
/home/lx/sortmerna/run/readb/fwd_0.fq.gz
648725915
15325159
1
fastq
/home/lx/sortmerna/run/readb/rev_0.fq.gz
948145087
15325159
1
fastq
/home/lx/sortmerna/run/readb/fwd_1.fq.gz
653543637
15325159
1
fastq
/home/lx/sortmerna/run/readb/rev_1.fq.gz
960648283
15325159
1
fastq
/home/lx/sortmerna/run/readb/fwd_2.fq.gz
656703365
15325158
1
fastq
/home/lx/sortmerna/run/readb/rev_2.fq.gz
918949395
15325158
1
fastq
/home/lx/sortmerna/run/readb/fwd_3.fq.gz
660974452
15325158
1
fastq
/home/lx/sortmerna/run/readb/rev_3.fq.gz
979528213
15325158
1
fastq`

**Comment by Sum-low** [comment]
sure. I’m sorry for not giving all the details.

```
`sortmerna -version
[process:1393] === Options processing starts ... ===
Found value: sortmerna
Found flag: -version
[process:1483] Processing option: version with value:

SortMeRNA version 4.3.6
Build Date: Aug 16 2022
sortmerna_build_git_sha:@db8c1983765f61986b46ee686734749eda235dcc@
sortmerna_build_git_date:@2022/08/16 11:42:59@

du -sh /home/lx/sortmerna/run/kvdb
2.4G    /home/lx/sortmerna/run/kvdb

ls -l /home/lx/sortmerna/run/kvdb
total 2487948
-rw-r--r-- 1 lx lx 67908158 Sep  5 02:31 000380.sst
-rw-r--r-- 1 lx lx 67896268 Sep  5 03:22 000521.sst
-rw-r--r-- 1 lx lx  1325539 Sep  5 03:33 000550.sst
-rw-r--r-- 1 lx lx 67918834 Sep  5 03:44 000582.sst
-rw-r--r-- 1 lx lx 67907219 Sep  5 03:45 000583.sst
-rw-r--r-- 1 lx lx 63747685 Sep  5 03:45 000584.sst
-rw-r--r-- 1 lx lx 67912701 Sep  5 03:50 000599.sst
-rw-r--r-- 1 lx lx 67907495 Sep  5 03:50 000600.sst
-rw-r--r-- 1 lx lx 67906611 Sep  5 03:50 000601.sst
-rw-r--r-- 1 lx lx 67915678 Sep  5 03:51 000604.sst
-rw-r--r-- 1 lx lx 67895296 Sep  5 03:51 000605.sst
-rw-r--r-- 1 lx lx 37021351 Sep  5 03:51 000606.sst
-rw-r--r-- 1 lx lx 67896148 Sep  5 04:01 000631.sst
-rw-r--r-- 1 lx lx 67906933 Sep  5 04:01 000632.sst
-rw-r--r-- 1 lx lx 67918086 Sep  5 04:01 000633.sst
-rw-r--r-- 1 lx lx 67906347 Sep  5 04:02 000636.sst
-rw-r--r-- 1 lx lx 55528663 Sep  5 04:02 000637.sst
-rw-r--r-- 1 lx lx 67885896 Sep  5 04:06 000649.sst
-rw-r--r-- 1 lx lx 67887596 Sep  5 04:06 000650.sst
-rw-r--r-- 1 lx lx 38743901 Sep  5 04:07 000651.sst
-rw-r--r-- 1 lx lx 67924755 Sep  5 04:12 000666.sst
-rw-r--r-- 1 lx lx 67905792 Sep  5 04:12 000667.sst
-rw-r--r-- 1 lx lx 67905833 Sep  5 04:12 000668.sst
-rw-r--r-- 1 lx lx 67905774 Sep  5 04:13 000669.sst
-rw-r--r-- 1 lx lx 65490327 Sep  5 04:13 000672.sst
-rw-r--r-- 1 lx lx 67906775 Sep  5 04:17 000684.sst
-rw-r--r-- 1 lx lx 67896277 Sep  5 04:18 000685.sst
-rw-r--r-- 1 lx lx 67891473 Sep  5 04:18 000686.sst
-rw-r--r-- 1 lx lx 67888510 Sep  5 04:18 000687.sst
-rw-r--r-- 1 lx lx 65573673 Sep  5 04:19 000690.sst
-rw-r--r-- 1 lx lx 67877713 Sep  5 04:27 000708.sst
-rw-r--r-- 1 lx lx 67883232 Sep  5 04:27 000709.sst
-rw-r--r-- 1 lx lx 67876846 Sep  5 04:27 000710.sst
-rw-r--r-- 1 lx lx 51679957 Sep  5 04:28 000712.sst
-rw-r--r-- 1 lx lx 11983534 Sep  5 04:28 000714.sst
-rw-r--r-- 1 lx lx 67900179 Sep  5 04:28 000715.sst
-rw-r--r-- 1 lx lx 45928402 Sep  5 04:29 000716.sst
-rw-r--r-- 1 lx lx 12010155 Sep  5 04:29 000718.sst
-rw-r--r-- 1 lx lx 12017383 Sep  5 04:31 000720.sst
-rw-r--r-- 1 lx lx 48018369 Sep  5 04:33 000721.log
-rw-r--r-- 1 lx lx 11998984 Sep  5 04:32 000722.sst
-rw-r--r-- 1 lx lx 67878081 Sep  5 04:32 000723.sst
-rw-r--r-- 1 lx lx 67881526 Sep  5 04:33 000724.sst
-rw-r--r-- 1 lx lx 55549697 Sep  5 04:33 000725.sst
-rw-r--r-- 1 lx lx       16 Sep  4 19:14 CURRENT
-rw-r--r-- 1 lx lx       36 Sep  4 19:14 IDENTITY
-rw-r--r-- 1 lx lx        0 Sep  4 19:14 LOCK
-rw-r--r-- 1 lx lx  1807582 Sep  5 04:33 LOG
-rw-r--r-- 1 lx lx    46669 Sep  5 04:32 MANIFEST-000004
-rw-r--r-- 1 lx lx     6504 Sep  4 19:14 OPTIONS-000007

du -sh /home/lx/sortmerna/run/readb
6.0G    /home/lx/sortmerna/run/readb

 ls -l /home/lx/sortmerna/run/readb
total 6276596
-rw-r--r-- 1 lx lx 648725915 Sep  4 22:36 fwd_0.fq.gz
-rw-r--r-- 1 lx lx 653543637 Sep  4 22:50 fwd_1.fq.gz
-rw-r--r-- 1 lx lx 656703365 Sep  4 23:04 fwd_2.fq.gz
-rw-r--r-- 1 lx lx 660974452 Sep  4 23:18 fwd_3.fq.gz
-rw-r--r-- 1 lx lx       971 Sep  4 23:18 readfeed
-rw-r--r-- 1 lx lx 948145087 Sep  4 22:36 rev_0.fq.gz
-rw-r--r-- 1 lx lx 960648283 Sep  4 22:50 rev_1.fq.gz
-rw-r--r-- 1 lx lx 918949395 Sep  4 23:04 rev_2.fq.gz
-rw-r--r-- 1 lx lx 979528213 Sep  4 23:18 rev_3.fq.gz

cat /home/lx/sortmerna/run/readb/readfeed
# format of this file:
#   time
#   num_orig_files
#   num_sense
#   num_splits
#   num_reads_tot
#   [
#     file
#     size
#     reads
#     zip
#     fastq/a
#   ] for each file both original and split

Wed Sep  4 23:18:50 2024

2
2
4
122601268
/home/lx/RIP_seq/fastq/trimmed/VIRMA_IP1_forward_val_1.fq.gz
2618337302
61300634
1
fastq
/home/lx/RIP_seq/fastq/trimmed/VIRMA_IP1_reverse_val_2.fq.gz
3805174809
61300634
1
fastq
/home/lx/sortmerna/run/readb/fwd_0.fq.gz
648725915
15325159
1
fastq
/home/lx/sortmerna/run/readb/rev_0.fq.gz
948145087
15325159
1
fastq
/home/lx/sortmerna/run/readb/fwd_1.fq.gz
653543637
15325159
1
fastq
/home/lx/sortmerna/run/readb/rev_1.fq.gz
960648283
15325159
1
fastq
/home/lx/sortmerna/run/readb/fwd_2.fq.gz
656703365
15325158
1
fastq
/home/lx/sortmerna/run/readb/rev_2.fq.gz
918949395
15325158
1
fastq
/home/lx/sortmerna/run/readb/fwd_3.fq.gz
660974452
15325158
1
fastq
/home/lx/sortmerna/run/readb/rev_3.fq.gz
979528213
15325158
1
fastq` 
```

**Comment by biocodz** [comment]
Your problem is very likely due a bug fixed in version [4.3.7](https://github.com/sortmerna/sortmerna/releases/tag/v4.3.7)
It's indeed due large file size, but not because of the memory, The size was read info a variable that could not accommodate it.
Please, try 4.3.7. Otherwise you would have to use large number of threads (like 20) to avoid this problem.

**Comment by Sum-low** [comment]
It still doesn't work properly. I tried running the same program in version 4.3.7, but encountered the same result(Segmentation fault (core dumped)).

Here are the code and results, along with some additional information.

```
sortmerna --ref /home/lx/sortmerna/sortmerna/data/rRNA_databases/silva-euk-18s-id95.fasta --ref /home/lx/sortmerna/sortmerna/data/rRNA_databases/silva-euk-28s-id98.fasta --reads /home/lx/RIP_seq/fastq/trimmed/VIRMA_IP1_forward_val_1.fq.gz --reads /home/lx/RIP_seq/fastq/trimmed/VIRMA_IP1_reverse_val_2.fq.gz --aligned /home/lx/RIP_seq/fastq/VIRMA_IP1_forward_rRNA --aligned /home/lx/RIP_seq/fastq/VIRMA_IP1_reverse_rRNA --other /home/lx/RIP_seq/fastq/VIRMA_IP1_forward_fliter --other /home/lx/RIP_se\q/fastq/VIRMA_IP1_reverse_fliter --fastx --threads 4
[process:1393] === Options processing starts ... ===
Found value: sortmerna
Found flag: --ref
Found value: /home/lx/sortmerna/sortmerna/data/rRNA_databases/silva-euk-18s-id95.fasta of previous flag: --ref
Found flag: --ref
Found value: /home/lx/sortmerna/sortmerna/data/rRNA_databases/silva-euk-28s-id98.fasta of previous flag: --ref
Found flag: --reads
Found value: /home/lx/RIP_seq/fastq/trimmed/VIRMA_IP1_forward_val_1.fq.gz of previous flag: --reads
Found flag: --reads
Found value: /home/lx/RIP_seq/fastq/trimmed/VIRMA_IP1_reverse_val_2.fq.gz of previous flag: --reads
Found flag: --aligned
Found value: /home/lx/RIP_seq/fastq/VIRMA_IP1_forward_rRNA of previous flag: --aligned
Found flag: --aligned
Found value: /home/lx/RIP_seq/fastq/VIRMA_IP1_reverse_rRNA of previous flag: --aligned
Found flag: --other
Found value: /home/lx/RIP_seq/fastq/VIRMA_IP1_forward_fliter of previous flag: --other
Found flag: --other
Found value: /home/lx/RIP_seq/fastq/VIRMA_IP1_reverse_fliter of previous flag: --other
Found flag: --fastx
Previous flag: --fastx is Boolean. Setting to True
Found flag: --threads
Found value: 4 of previous flag: --threads
[process:1483] Processing option: aligned with value: /home/lx/RIP_seq/fastq/VIRMA_IP1_forward_rRNA
[process:1483] Processing option: aligned with value: /home/lx/RIP_seq/fastq/VIRMA_IP1_reverse_rRNA
[process:1483] Processing option: fastx with value:
[process:1483] Processing option: other with value: /home/lx/RIP_seq/fastq/VIRMA_IP1_forward_fliter
[process:1483] Processing option: other with value: /home/lx/RIP_seq/fastq/VIRMA_IP1_reverse_fliter
[process:1483] Processing option: reads with value: /home/lx/RIP_seq/fastq/trimmed/VIRMA_IP1_forward_val_1.fq.gz
[opt_reads:98] Processing reads file [1] out of total [2] files
[process:1483] Processing option: reads with value: /home/lx/RIP_seq/fastq/trimmed/VIRMA_IP1_reverse_val_2.fq.gz
[opt_reads:98] Processing reads file [2] out of total [2] files
[process:1483] Processing option: ref with value: /home/lx/sortmerna/sortmerna/data/rRNA_databases/silva-euk-18s-id95.fasta
[opt_ref:158] Processing reference [1] out of total [2] references
[opt_ref:206] File "/home/lx/sortmerna/sortmerna/data/rRNA_databases/silva-euk-18s-id95.fasta" exists and is readable
[process:1483] Processing option: ref with value: /home/lx/sortmerna/sortmerna/data/rRNA_databases/silva-euk-28s-id98.fasta
[opt_ref:158] Processing reference [2] out of total [2] references
[opt_ref:206] File "/home/lx/sortmerna/sortmerna/data/rRNA_databases/silva-euk-28s-id98.fasta" exists and is readable
[process:1483] Processing option: threads with value: 4
[process:1503] === Options processing done ===
[process:1504] Alignment type: [best:1 num_alignments:1 min_lis:2 seeds:2]
[validate_kvdbdir:1242] 'workdir' option was not provided. Using USERDIR to set the working directory: ""
[validate_kvdbdir:1248] Key-value DB location "/home/lx/sortmerna/run/kvdb"
[validate_kvdbdir:1284] Creating KVDB directory: "/home/lx/sortmerna/run/kvdb"
[validate_idxdir:1214] Using index directory: "/home/lx/sortmerna/run/idx"
[validate_idxdir:1222] Created index directory - OK
[validate_readb_dir:1306] Using split reads directory : "/home/lx/sortmerna/run/readb"
[validate_readb_dir:1314] Created split reads directory - OK
[main:62] Running command:
sortmerna --ref /home/lx/sortmerna/sortmerna/data/rRNA_databases/silva-euk-18s-id95.fasta --ref /home/lx/sortmerna/sortmerna/data/rRNA_databases/silva-euk-28s-id98.fasta --reads /home/lx/RIP_seq/fastq/trimmed/VIRMA_IP1_forward_val_1.fq.gz --reads /home/lx/RIP_seq/fastq/trimmed/VIRMA_IP1_reverse_val_2.fq.gz --aligned /home/lx/RIP_seq/fastq/VIRMA_IP1_forward_rRNA --aligned /home/lx/RIP_seq/fastq/VIRMA_IP1_reverse_rRNA --other /home/lx/RIP_seq/fastq/VIRMA_IP1_forward_fliter --other /home/lx/RIP_seq/fastq/VIRMA_IP1_reverse_fliter --fastx --threads 4
[build_index:1123] ==== Index building started ====
[build_index:1180] Begin indexing file /home/lx/sortmerna/sortmerna/data/rRNA_databases/silva-euk-18s-id95.fasta of size: 13259584 under index name /home/lx/sortmerna/run/idx/2700646386527218729
  done.

[build_index:1180] Begin indexing file /home/lx/sortmerna/sortmerna/data/rRNA_databases/silva-euk-28s-id98.fasta of size: 14945070 under index name /home/lx/sortmerna/run/idx/1845323523482939374
  done.

[build_index:2091] ==== Done index building in 61.3703 sec ====

[init:108] Readfeed init started
[define_format:881] file: "/home/lx/RIP_seq/fastq/trimmed/VIRMA_IP1_forward_val_1.fq.gz" is FASTQ gzipped
[define_format:881] file: "/home/lx/RIP_seq/fastq/trimmed/VIRMA_IP1_reverse_val_2.fq.gz" is FASTQ gzipped
[count_reads:915] started count  ...
[next:322] EOF FWD reached. Total reads: 61300634
[next:322] EOF REV reached. Total reads: 61300634
[count_reads:945] done count. Elapsed time: 2760.86 sec. Total reads: 122601268
[init_split_files:967] added file: /home/lx/sortmerna/run/readb/fwd_0.fq.gz
[init_split_files:967] added file: /home/lx/sortmerna/run/readb/rev_0.fq.gz
[init_split_files:967] added file: /home/lx/sortmerna/run/readb/fwd_1.fq.gz
[init_split_files:967] added file: /home/lx/sortmerna/run/readb/rev_1.fq.gz
[init_split_files:967] added file: /home/lx/sortmerna/run/readb/fwd_2.fq.gz
[init_split_files:967] added file: /home/lx/sortmerna/run/readb/rev_2.fq.gz
[init_split_files:967] added file: /home/lx/sortmerna/run/readb/fwd_3.fq.gz
[init_split_files:967] added file: /home/lx/sortmerna/run/readb/rev_3.fq.gz
[split:605] start splitting. Using number of splits equals number of processing threads: 4

[next:322] EOF FWD reached. Total reads: 61300634
[next:322] EOF REV reached. Total reads: 61300634
[split:717] Done splitting. Reads count: 122601268 Runtime sec: 1938.16

[init:135] Readfeed init done in sec [4699.09]
[store_to_db:292] Stored Reads statistics to DB:
     all_reads_count= 122601268 all_reads_len= 15260118355 min_read_len= 50 max_read_len= 150 total_aligned= 0 total_aligned_id= 0 total_aligned_cov= 0 total_aligned_id_cov= 0 total_denovo= 0 num_short= 0 reads_matched_per_db= TODO is_stats_calc= 0 is_total_reads_mapped_cov= 0

[align:143] ==== Starting alignment ====
[align:146] Number of cores: 8
[align:163] Using number of Processor threads: 4
[Refstats:60] Index Statistics calculation starts ... done in: 0.707715 sec
[align:185] Loading index: 0 part: 1/1 Memory KB: 414 ...
[align:190] done in [0.540882] sec Memory KB: 479
[align:193] Loading references ...
[align:197] done in [0.0173458] sec. Memory KB: 479
[align2:70] Processor 0 thread 139816687568640 started
[align2:70] Processor 3 thread 139817081767680 started
[align2:70] Processor 1 thread 139816771061504 started
[align2:70] Processor 2 thread 139816779515648 started
[next:455] EOF FWD reached. Total reads: 15325158
[next:455] EOF REV reached. Total reads: 15325158
[align2:133] Processor 2 thread 139816779515648 done. Processed 30650316 reads. Skipped already processed: 0 reads Aligned reads (passing E-value): 7163079 Runtime sec: 6685.22
[next:455] EOF FWD reached. Total reads: 15325159
[next:455] EOF REV reached. Total reads: 15325159
[align2:133] Processor 0 thread 139816687568640 done. Processed 30650318 reads. Skipped already processed: 0 reads Aligned reads (passing E-value): 7156628 Runtime sec: 6793.34
[next:455] EOF FWD reached. Total reads: 15325159
[next:455] EOF REV reached. Total reads: 15325159
[align2:133] Processor 1 thread 139816771061504 done. Processed 30650318 reads. Skipped already processed: 0 reads Aligned reads (passing E-value): 7192186 Runtime sec: 6901.65
[next:455] EOF FWD reached. Total reads: 15325158
[next:455] EOF REV reached. Total reads: 15325158
[align2:133] Processor 3 thread 139817081767680 done. Processed 30650316 reads. Skipped already processed: 0 reads Aligned reads (passing E-value): 7179987 Runtime sec: 7099.18
[align:220] done index: 0 part: 1 in 7099.18 sec Memory KB: 13293
[align:227] Index and References unloaded in 0.0952215 sec. Memory KB: 13293
[align:185] Loading index: 1 part: 1/1 Memory KB: 13293 ...
[align:190] done in [1.95065] sec Memory KB: 13296
[align:193] Loading references ...
[align:197] done in [0.0896403] sec. Memory KB: 13300
[align2:70] Processor 0 thread 139817081767680 started
[align2:70] Processor 1 thread 139816779515648 started
[align2:70] Processor 2 thread 139816771061504 started
[align2:70] Processor 3 thread 139816687568640 started
Segmentation fault (core dumped)


sortmerna -version
[process:1393] === Options processing starts ... ===
Found value: sortmerna
Found flag: -version
[process:1483] Processing option: version with value:

SortMeRNA version 4.3.7
Build Date: Aug  2 2024
sortmerna_build_git_sha:@0@
sortmerna_build_git_date:@2024/08/02 14:52:06@


 du -sh /home/lx/sortmerna/run/kvdb
4.8G    /home/lx/sortmerna/run/kvdb



ls -l /home/lx/sortmerna/run/kvdb
total 4949296
-rw-r--r-- 1 lx lx 67919536 Sep  6 17:06 000357.sst
-rw-r--r-- 1 lx lx 67926330 Sep  6 17:11 000375.sst
-rw-r--r-- 1 lx lx 67899806 Sep  6 17:17 000391.sst
-rw-r--r-- 1 lx lx 67913867 Sep  6 17:22 000408.sst
-rw-r--r-- 1 lx lx 38597526 Sep  6 17:23 000410.sst
-rw-r--r-- 1 lx lx 67894669 Sep  6 17:28 000427.sst
-rw-r--r-- 1 lx lx 67906555 Sep  6 17:33 000445.sst
-rw-r--r-- 1 lx lx 67895348 Sep  6 17:39 000462.sst
-rw-r--r-- 1 lx lx 67907760 Sep  6 17:50 000497.sst
-rw-r--r-- 1 lx lx 28237146 Sep  6 17:50 000498.sst
-rw-r--r-- 1 lx lx 67905634 Sep  6 17:56 000517.sst
-rw-r--r-- 1 lx lx 67885130 Sep  6 17:56 000518.sst
-rw-r--r-- 1 lx lx 67906511 Sep  6 18:07 000552.sst
-rw-r--r-- 1 lx lx 47958349 Sep  6 18:07 000553.sst
-rw-r--r-- 1 lx lx 46094421 Sep  6 18:13 000571.sst
-rw-r--r-- 1 lx lx 67894308 Sep  6 18:18 000588.sst
-rw-r--r-- 1 lx lx 67900540 Sep  6 18:18 000589.sst
-rw-r--r-- 1 lx lx 23913110 Sep  6 18:18 000590.sst
-rw-r--r-- 1 lx lx 67887326 Sep  6 18:29 000623.sst
-rw-r--r-- 1 lx lx 67929959 Sep  6 18:30 000625.sst
-rw-r--r-- 1 lx lx 67906050 Sep  6 18:30 000626.sst
-rw-r--r-- 1 lx lx 67905180 Sep  6 18:30 000629.sst
-rw-r--r-- 1 lx lx 67913691 Sep  6 18:30 000630.sst
-rw-r--r-- 1 lx lx  9086311 Sep  6 18:30 000631.sst
-rw-r--r-- 1 lx lx  6218288 Sep  6 18:34 000638.sst
-rw-r--r-- 1 lx lx  5866272 Sep  6 18:39 000654.sst
-rw-r--r-- 1 lx lx 67891110 Sep  6 18:40 000663.sst
-rw-r--r-- 1 lx lx 67888247 Sep  6 18:40 000664.sst
-rw-r--r-- 1 lx lx 44464143 Sep  6 18:41 000665.sst
-rw-r--r-- 1 lx lx  6123263 Sep  6 18:45 000674.sst
-rw-r--r-- 1 lx lx  6299157 Sep  6 18:50 000691.sst
-rw-r--r-- 1 lx lx 37411713 Sep  6 18:51 000701.sst
-rw-r--r-- 1 lx lx 67906344 Sep  6 18:51 000702.sst
-rw-r--r-- 1 lx lx 45303008 Sep  6 18:51 000703.sst
-rw-r--r-- 1 lx lx  6191478 Sep  6 18:55 000712.sst
-rw-r--r-- 1 lx lx  2453268 Sep  6 18:56 000721.sst
-rw-r--r-- 1 lx lx 67895524 Sep  6 18:56 000722.sst
-rw-r--r-- 1 lx lx 63115868 Sep  6 18:57 000723.sst
-rw-r--r-- 1 lx lx  5837001 Sep  6 19:01 000732.sst
-rw-r--r-- 1 lx lx  6068557 Sep  6 19:06 000748.sst
-rw-r--r-- 1 lx lx 67905699 Sep  6 19:07 000756.sst
-rw-r--r-- 1 lx lx 52420095 Sep  6 19:07 000757.sst
-rw-r--r-- 1 lx lx 50110807 Sep  6 19:13 000764.log
-rw-r--r-- 1 lx lx  6236780 Sep  6 19:12 000766.sst
-rw-r--r-- 1 lx lx 39439727 Sep  6 19:12 000767.sst
-rw-r--r-- 1 lx lx 64066077 Sep  6 19:12 000768.sst
-rw-r--r-- 1 lx lx 61292138 Sep  6 19:12 000769.sst
-rw-r--r-- 1 lx lx 39136383 Sep  6 19:12 000770.sst
-rw-r--r-- 1 lx lx  5922308 Sep  6 19:12 000771.sst
-rw-r--r-- 1 lx lx 25830703 Sep  6 19:12 000772.sst
-rw-r--r-- 1 lx lx 21215609 Sep  6 19:12 000773.sst
-rw-r--r-- 1 lx lx 67906330 Sep  6 19:12 000774.sst
-rw-r--r-- 1 lx lx 50313334 Sep  6 19:13 000775.sst
-rw-r--r-- 1 lx lx       16 Sep  6 12:46 CURRENT
-rw-r--r-- 1 lx lx       36 Sep  6 12:46 IDENTITY
-rw-r--r-- 1 lx lx        0 Sep  6 12:46 LOCK
-rw-r--r-- 1 lx lx  1927117 Sep  6 19:12 LOG
-rw-r--r-- 1 lx lx    67250 Sep  6 19:12 MANIFEST-000005
-rw-r--r-- 1 lx lx     6906 Sep  6 12:46 OPTIONS-000007



du -sh /home/lx/sortmerna/run/readb
6.0G    /home/lx/sortmerna/run/readb




 ls -l /home/lx/sortmerna/run/readb
total 6277264
-rw-r--r-- 1 lx lx 648725915 Sep  6 13:40 fwd_0.fq.gz
-rw-r--r-- 1 lx lx 653543637 Sep  6 13:49 fwd_1.fq.gz
-rw-r--r-- 1 lx lx 656703365 Sep  6 13:56 fwd_2.fq.gz
-rw-r--r-- 1 lx lx 660974452 Sep  6 14:05 fwd_3.fq.gz
-rw-r--r-- 1 lx lx       971 Sep  6 14:05 readfeed
-rw-r--r-- 1 lx lx 948145087 Sep  6 13:40 rev_0.fq.gz
-rw-r--r-- 1 lx lx 960648283 Sep  6 13:49 rev_1.fq.gz
-rw-r--r-- 1 lx lx 918949395 Sep  6 13:56 rev_2.fq.gz
-rw-r--r-- 1 lx lx 979528213 Sep  6 14:05 rev_3.fq.gz





 cat /home/lx/sortmerna/run/readb/readfeed
# format of this file:
#   time
#   num_orig_files
#   num_sense
#   num_splits
#   num_reads_tot
#   [
#     file
#     size
#     reads
#     zip
#     fastq/a
#   ] for each file both original and split

Fri Sep  6 14:05:07 2024

2
2
4
122601268
/home/lx/RIP_seq/fastq/trimmed/VIRMA_IP1_forward_val_1.fq.gz
2618337302
61300634
1
fastq
/home/lx/RIP_seq/fastq/trimmed/VIRMA_IP1_reverse_val_2.fq.gz
3805174809
61300634
1
fastq
/home/lx/sortmerna/run/readb/fwd_0.fq.gz
648725915
15325159
1
fastq
/home/lx/sortmerna/run/readb/rev_0.fq.gz
948145087
15325159
1
fastq
/home/lx/sortmerna/run/readb/fwd_1.fq.gz
653543637
15325159
1
fastq
/home/lx/sortmerna/run/readb/rev_1.fq.gz
960648283
15325159
1
fastq
/home/lx/sortmerna/run/readb/fwd_2.fq.gz
656703365
15325158
1
fastq
/home/lx/sortmerna/run/readb/rev_2.fq.gz
918949395
15325158
1
fastq
/home/lx/sortmerna/run/readb/fwd_3.fq.gz
660974452
15325158
1
fastq
/home/lx/sortmerna/run/readb/rev_3.fq.gz
979528213
15325158
1
fastq
```

**Comment by biocodz** [comment]
I'll try to create a similar setup to see if it can be reproduced

**Comment by biocodz** [comment]
Now we are at release 7.0.0, so closing this one ...
